services:
  frontend:
    image: nginx:1.26.3
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NGINX_PORT=80 # 设置环境变量
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ] # 健康检查命令
      interval: 10s # 检查间隔
      timeout: 30s # 超时时间
      retries: 5 # 重试次数
      start_period: 30s # 启动等待时间
